### ISSUE TITLE
Problem with roads shape file

### ISSUE THREAD

**Issue by doorleyr** [CityScope/CSL_Helsinki#4]
The reason the agents were not moving was that there were no roads in the area and the agents were constrained to move on roads. There seems to be an issue with the roads shape file. Even when I open the buildings and roads shape files together in QGIS I can see that they are not in the same area. It might be that the wrong projection is specified.

I changed the constant 'moveOnRoads' to false in the simulation so that now the agents will move in straight lines between the buildings. When we have the proper shape files we can change this back.

**Comment by agrignard** [comment]
This is a typical problem when the road network is not totally connected. setting moveOnRoads is one option but of course having a connected road network is what we aim for.

We have implemeted in GAMA a model that connect a 'non connected road shapefile.

You can have a look at this one Library Models/Features/Data Cleaning/models

**Comment by doorleyr** [comment]
I don't think connectivity of the network is the main issue. If you run the simulation and then inspect the road 'agents' you see that the road network is somewhere far outside of the simulation area. Even opening the shape files in QGIS, you can see that the buildings shape file and the roads shape file are not in the same place. I think there's some inconsistency with the projections of the shape files.  @sannailtanen can you look into this and make sure all the projections are correct?

Setting moveOnRoads to False was just a temporary solution so we could see how things are working otherwise but of course we need to solve the actual issue.
