### ISSUE TITLE
Genericity of the code, GitHib Workflow.

### ISSUE THREAD

**Issue by agrignard** [CityScope/CSL_Helsinki#5]
Dear all,

Very good job for the effort of pushing code in the Helsinki Github, this is a great news! Welcome to the CityScope community!

It seems that one first step is to have kind of reproduction of the volpe model but for Helsinki, right?

For now what has been done is that the Helsinki Repo  https://github.com/CityScope/CSL_Helsinki/tree/master/CS_Gama_Aalto/CS_Simulation_GAMA-master is a hard copy of the generic volpe model from this repo
https://github.com/CityScope/CS_Simulation_GAMA. 

Having 2 version of the same model will make it very difficult to maitain and we will lose all the benefit of the genericity and the github worlflow. A classical github workflow would be easer (i) to fork the intial repo, or (ii) create a branch in the intial repo and (iii) creat a submodule in the helsinki module that point to the original one. 

I just want to insist that this GAMA model has been designed in a generic way so that it can run on any cities as soon as the GIS is compatible with the API (see https://github.com/CityScope/CS_Simulation_GAMA/wiki/GIS-Structure)

If you go to the dev branch you can see that there is this folder
https://github.com/CityScope/CS_Simulation_GAMA/tree/devEnergy/CS_CityScope_GAMA/includes/City where all the compatible GIS city are stored. Ideally the Compatible Helsinki/aalto file should be stored here 

@doorleyr can you take the lead on making this architecture happen? Personnally I think that option (iii) submodule is maybe the most appropriate but we can speak about it.

Later we could  imaging that if you are developping a new generic feature it could be added to the intial model through a pull request.

This design will  more powerful for the CityScience Netwok approach collaboration and will give also much more visibility to the different contribution

We can discuss about this in a Skype if you want.

**Comment by doorleyr** [comment]
Yes, the plan is to (i) create a replica of the current Volpe model using Helsinki data and then (ii) adapt the simulation logic to suit their particular research questions and the connections between people profiles and land uses.

I agree it would be best if we can use the exact same repo and just add another city data folder. However, the reasons why we copied it were (i)  we plan to edit the simulation logic later and (ii) there are some lines of code in the CityScope_main.gaml which are specific to Volpe. For example, this block of code:

	// Variables used to initialize the table's grid.
	float angle <- -9.74;
	point center <- {1007, 632};
	float brickSize <- 21.3;
	// Online City IO server to query data from.
	string CITY_IO_URL <- "https://cityio.media.mit.edu/api/table/citymatrix_volpe";
	// Offline backup data to use when server data unavailable.
	string KENDALL_DATA <- "../includes/cityIO_Kendall.json”;

Maybe, this can be solved by adding another file in includes like a configuration file? Or ideally it should be set based on the ’spatial’ data in the cityIO json. What do you think?

**Comment by agrignard** [comment]
Yep you're right. Ideally the settings shoudl come from cityIO even if in some case you light run to run this model without a corresponfind physical grid.

I will work on a way to put those information at least in a file so that we can have different configuration per city.

See https://github.com/CityScope/CS_Simulation_GAMA/issues/37

**Comment by doorleyr** [comment]
The Aalto Gama model is now living in the CS_Simulation_GAMA repo so closing this issue.
