### ISSUE TITLE
Types sent by scanner are inconsistent with types expected by model

### ISSUE THREAD

**Issue by doorleyr** [CityScope/CSL_Helsinki#8]
The land use type codes expected by the GAMA model are defined in the citymatrix_map_settings variable (line 48). However, these are not the same set of codes currently being sent to cityIO. You need to either send the same codes as the model expects or change the citymatrix_map_settings variable to match the codes you're sending.

**Comment by agrignard** [comment]
See my previous comment on the genericity of the model. The format 2.1 is meant to give the possibility to explicit what are the data sent, what you call ````citymatrix_map_settings`````should be read from the cityIO file.

@doorleyr "The land use type codes expected by the GAMA model are defined in the citymatrix_map_settings variable (line 48)" can you point to the file your are mentionning? What do you mean by the GAMA model?

**Comment by doorleyr** [comment]
The Aalto Gama model is now living in the CS_Simulation_GAMA repo so closing this issue.
